### ISSUE TITLE
You exceeded your current quota, please check your plan and billing details., Retrying in 20 seconds.

### ISSUE THREAD

**Issue by WhistleSpread** [zwq2018/Data-Copilot#1]
I really appreciate your work, but when I try this app, I run into this problem "You exceeded your current quota, please check your plan and billing details., Retrying in 20 seconds.", it seems like the problem of my openai_key, even if I renewed my openai_key, do you have any suggestions to fix this problem ?

**Comment by zwq2018** [comment]
If you enter the official key of openai, please make sure the format is correct (sk-XXXXX) and that the account balance is available.
I just checked and the app is working fine. After entering the key, please press the OK button, then enter your question and click start.

**Comment by zwq2018** [comment]
If there are still questions, please do not hesitate to contact me at

**Comment by lwclover** [comment]
> If you enter the official key of openai, please make sure the format is correct (sk-XXXXX) and that the account balance is available. I just checked and the app is working fine. After entering the key, please press the OK button, then enter your question and click start.

I get the same message "You exceeded your current quota, please check your plan and billing details., Retrying in 80 seconds..."

**Comment by lwclover** [comment]
> If you enter the official key of openai, please make sure the format is correct (sk-XXXXX) and that the account balance is available. I just checked and the app is working fine. After entering the key, please press the OK button, then enter your question and click start.

How can free-riders use it?
