### ISSUE TITLE
Outputting Figure from Main.py Source Code and Seeking Feedback/Correction

### ISSUE THREAD

**Issue by yezhwi** [zwq2018/Data-Copilot#13]
Read the source code of main.py, output the figure below, hoping to help friends who want to read the source code, also hoping to correct any errors. 😊

<img width="920" alt="image" src="https://github.com/zwq2018/Data-Copilot/assets/7806683/4fb6644e-988b-4208-90ec-d2a6419c81ff">

**Comment by zwq2018** [comment]
Thank you very much for the flowchart you created. You can submit a pull request, and I will add this diagram to the readme.

**Comment by yezhwi** [comment]
> Thank you very much for the flowchart you created. You can submit a pull request, and I will add this diagram to the readme.

👌，😊
