### ISSUE TITLE
执行main方法时，折线图能正常显示。执行app在可视化界面上，折线图是一张空的全白图。

### ISSUE THREAD

**Issue by liguangyuaaa** [zwq2018/Data-Copilot#15]
在执行app.py时，最后的日志是这个：StopIteration。

**Comment by zwq2018** [comment]
听着像是gradio的问题，你检查下gradio是否正常，网页里打印的step log有么？只有最后图片显示空白？

**Comment by zwq2018** [comment]
StopIteration这个日志没问题的。如果gradio的网页里其他都是正常显示，运行过程的solving step那些也正常，只有最后图像无法显示的话，那就是gradio的版本或者你自己浏览器的问题。建议先检测下

**Comment by liguangyuaaa** [comment]
改成这个就可以了：pip install gradio==3.28.0；我的python是3.9的；非常感谢
