### ISSUE TITLE
Generated an exception: 抱歉，您没有访问该接口的权限，权限的具体详情访问：https://tushare.pro/document/1?doc_id=108。

### ISSUE THREAD

**Issue by bzqweiyi** [zwq2018/Data-Copilot#17]
Would you pls share the tushare token for us? when use the instruction '预测未来中国4个季度的GDP增长率', it will call the tool api. 
Many thx! 

step: step1=
content: {
 "arg1": ["2000101","20230707","gdp_yoy"],
 "function1": "get_GDP_data",
 "output1": "result1",
 "description1": "gdp同比增速数据"
}
It has parallel steps: 1.0
Traceback (most recent call last):
  File "D:/workspace/02_from_git/Data-Copilot/main.py", line 380, in <module>
    output, image, df, output_result = run(instruction, send_chat_request_Azure=openai_call, openai_key=openai_key, api_base='', engine='')
  File "D:/workspace/02_from_git/Data-Copilot/main.py", line 273, in run
    Previous_result[rename] = result_buffer[output_name][1]
KeyError: 'result2'
Generated an exception: 抱歉，您没有访问该接口的权限，权限的具体详情访问：https://tushare.pro/document/1?doc_id=108。
==================

step: step2=
content: {
 "arg1": ["result1","gdp_yoy",4],
 "function1": "predict_next_value",
 "output1": "result2",
 "description1": "未来4个季度gdp同比增速数据预测数据"
}
It has parallel steps: 1.0
Generated an exception: 'result1'
===============================Visualization Stage===========================================

Process finished with exit code 1

**Comment by zwq2018** [comment]
Sorry, tushare key needs to be provided by you, I am using my own purchased account.
Besides, different data sources may involve keys with different privileges.
You can use the free demos we offer on Huggingface Space

**Comment by bzqweiyi** [comment]
ok, many thx, would you pls share the Huggingface Space demo link for us.

**Comment by zwq2018** [comment]
<img width="1088" alt="image" src="https://github.com/zwq2018/Data-Copilot/assets/44236100/23fec517-cda5-4be9-a71a-fa194e1f51d0">

**Comment by zwq2018** [comment]
https://huggingface.co/spaces/zwq2018/Data-Copilot

**Comment by bzqweiyi** [comment]
many thx
