### ISSUE TITLE
What should I do if I want to use my own dataset

### ISSUE THREAD

**Issue by cold-rivers** [zwq2018/Data-Copilot#2]
Do I need to modify some interfaces?

**Comment by zwq2018** [comment]
If you want to use your own data source, it is better to re-implement the whole process of interface creation and interface invocation.
Or another approach, you can use my interface but replace the data source api in the interface. But this may lead to some inconsistencies in the format of the data

**Comment by cold-rivers** [comment]
Thanks for the reply，I will give it a try
