### ISSUE TITLE
关于接口设计部分问题请教

### ISSUE THREAD

**Issue by downeykking** [zwq2018/Data-Copilot#26]
您好！想请问下在接口设计部分，您提到了通过种子request来self-instruct得到更多的request，请问这个过程应该需要生成多少量级的新request才可以比较好的完成接口定义部分呢？以及self-request，interface implemantation这两部分的prompt词您方便提供吗？谢谢！

**Comment by zwq2018** [comment]
生成多少量级的request取决于你接入的数据丰富程度和用户需求多样性。我实验里demo比较简单，我用20条手动编写的种子request和几十个关键词，一共生成了500多条，基本是扩大了一个数量级，基本能覆盖了我想表达的需求

但是我的需求其实也比较有限，数据也是tushare里提供的已经很标准格式化的数据，需求稍微变一下接口就不够用了. 所以我觉得一个数量级是不够的, 太影响后面的接口设计通用性.

然后基于这些需求，来回倒几轮可以完成接口设计

论文后面的附录里提供了一些prompt设计的模板，具体的这个取决于数据和需求，给了也很难能用，我这个金融的你也不一定能用上，大概思想就是让LLM自己编需求，或者根据关键词编需求。
除了self-instruct，wizard-LM你也可以看看.

**Comment by downeykking** [comment]
> 生成多少量级的request取决于你接入的数据丰富程度和用户需求多样性。我实验里demo比较简单，我用20条手动编写的种子request和几十个关键词，一共生成了500多条，基本是扩大了一个数量级，基本能覆盖了我想表达的需求
> 
> 但是我的需求其实也比较有限，数据也是tushare里提供的已经很标准格式化的数据，需求稍微变一下接口就不够用了. 所以我觉得一个数量级是不够的, 太影响后面的接口设计通用性.
> 
> 然后基于这些需求，来回倒几轮可以完成接口设计
> 
> 论文后面的附录里提供了一些prompt设计的模板，具体的这个取决于数据和需求，给了也很难能用，我这个金融的你也不一定能用上，大概思想就是让LLM自己编需求，或者根据关键词编需求。 除了self-instruct，wizard-LM你也可以看看.

好的 谢谢！
