### ISSUE TITLE
本地无法运行app.py

### ISSUE THREAD

**Issue by sharejing** [zwq2018/Data-Copilot#3]
您好，我本地按照步骤操作，一直报错，请问怎么解决了，谢谢！
![image](https://github.com/zwq2018/Data-Copilot/assets/33115703/4c1a2acc-7340-48bc-b8dc-a7b41c35c8c3)

![image](https://github.com/zwq2018/Data-Copilot/assets/33115703/5434e07e-aeb0-45b8-90f0-828a137bc165)

**Comment by sharejing** [comment]
> 

嗯嗯，是的，app.py代码无报错，gradio一直报error。只填openai的key也不行

![image](https://github.com/zwq2018/Data-Copilot/assets/33115703/072e47ab-f5b2-495d-bcdd-f2247353a321)

**Comment by sharejing** [comment]
> tushare的key填了吧？直接跑main.py可以么。你gradio显示error时打印的报错是啥啊

嗯嗯，tushare说权限不够，我目前是120积分，访问下面的数据需要更高积分吗？

![image](https://github.com/zwq2018/Data-Copilot/assets/33115703/a76682d3-8545-4da5-9ef0-24aae5c338aa)

**Comment by zwq2018** [comment]
嗯需要更高积分一些数据，最好都到2000
