### ISSUE TITLE
未响应

### ISSUE THREAD

**Issue by rsghll** [zwq2018/Data-Copilot#31]
遇到一个问题，我在本地启动 app.py ,已经在tool.py 中填入 tushare.pro 的 token，然后在gradio页面填入 key api base engine，点击 ok后已经显示一直在加载，后台也没看见什么信息。

![image](https://github.com/zwq2018/Data-Copilot/assets/59009945/307a9a69-b669-44d8-94e5-bb0ce7988edd)

**Comment by zwq2018** [comment]
检查下你的key可以用
debug下卡在哪步了
正常情况下是可以跑

**Comment by rsghll** [comment]
感谢
