### ISSUE TITLE
图像显示不出来

### ISSUE THREAD

**Issue by H9990HH969** [zwq2018/Data-Copilot#33]
按照要求进行布置环境后，其他都正常，就是图像显示不出来。
运行的是类似于”给我画一下可孚医疗2022年年中到今天的股价“这种指令
![b1ff1daf318727f9f4d87d71a15e6f0](https://github.com/zwq2018/Data-Copilot/assets/133352113/a3beedf2-447c-4aa1-b763-0e367de710b6)

**Comment by zwq2018** [comment]
这个可能是版本问题，gradio的版本不对可能是会有这个问题。你重新装下

**Comment by H9990HH969** [comment]
@zwq2018  我装的版本应该是挺新的，请问你是用的什么版本
![1691733206564](https://github.com/zwq2018/Data-Copilot/assets/133352113/9cada781-741d-416f-b5e4-7485c10383a7)

**Comment by zwq2018** [comment]
https://github.com/zwq2018/Data-Copilot/issues/15
你可以参考下这个issue
你本地跑main能显示么

**Comment by H9990HH969** [comment]
还真是，gradio不能太新，装的时候，最好就装3.28.0
