### ISSUE TITLE
自己定义函数，让llm选择是这样吗？

### ISSUE THREAD

**Issue by lcyuanjiang** [zwq2018/Data-Copilot#34]
这是提供一个框架么

**Comment by lcyuanjiang** [comment]
每个意图对应固定的一系列自己写的函数对吗？

**Comment by zwq2018** [comment]
不是, 你认真看论文吧。LLM设计接口函数，然后自己调用

**Comment by zwq2018** [comment]
> 每个意图对应固定的一系列自己写的函数对吗？

先分析种子意图，然后模拟生成大量需求，然后基于需求总结设计函数接口。最后基于设计好的函数接口做调用

**Comment by lcyuanjiang** [comment]
感谢回答。  我拜读下paper

**Comment by yysirs** [comment]
> 每个意图对应固定的一系列自己写的函数对吗？

如果对每个意图都很熟悉了解，自己写也可以的，本质上来讲让LLM模拟生成需求，也是尽量覆盖所有可能的意图需求。

**Comment by zwq2018** [comment]
> > 每个意图对应固定的一系列自己写的函数对吗？
> 
> 如果对每个意图都很熟悉了解，自己写也可以的，本质上来讲让LLM模拟生成需求，也是尽量覆盖所有可能的意图需求。

感谢回复
