### ISSUE TITLE
如何做某专业领域的数据分析助手？

### ISSUE THREAD

**Issue by lizhengwei1992** [zwq2018/Data-Copilot#4]
感谢开源贡献！
最近对大语言模型的应用很感兴趣，想请教下两个问题，
1、如果想做某个垂直专业领域的数据报表分析（比如某些生产过程中的指标数据等等），如何参考这个项目做适配？主要是修改处理数据源的方法？
2、基座大语言模型可以换成开源的大语言模型吗？比如ChatGLM系列 或者 LLama系列？

期待能给一些思路！感谢！

**Comment by zwq2018** [comment]
good question
1-做垂类领域的data-copilot需要两个地方修改：1）新的工具接口，2）工具调用的demonstration。不同的domain数据差异还挺大的，所以最好按照论文里面的方法完整走一遍整个设计过程，即从先接入新的数据源，然后做self-request的接口设计，然后得到接口工具后设计一些demonstration在prompt-lib里
2-当前还不支持其他的基座模型，主要是基座模型的接口调度和规划的效果其实有点差
