### ISSUE TITLE
Error：'MyThread' object has no attribute 'result'

### ISSUE THREAD

**Issue by ET-yzk** [zwq2018/Data-Copilot#50]
刚刚在huggingface平台上试了自己写例子和使用官方的例子，程序最终都在工具选择阶段显示“'MyThread' object has no attribute 'result'”

**Comment by zwq2018** [comment]
huggingface的 space 已经停了，api 开销太大了。 本地自己部署是可以跑的，出现这个问题可能是格式上有些问题，你 debug 下就可以

**Comment by zmsoft** [comment]
@zwq2018 @ET-yzk  我是本地运行app.py，报上面这个错误，请问是什么原因导致的？



```python send_chat_request_Azure
===============================Intent Detecting===========================================
Exception in thread Thread-12:
Traceback (most recent call last):
  File "/xxx/miniconda3/envs/data_copilot/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/xxx/Data-Copilot/main.py", line 37, in run
    self.result = self.func(*self.args)
  File "/xxx/Data-Copilot/main.py", line 135, in run
    prompt_intent_detection = prompt_intent_detection + '\n\n' + 'Instruction:' + '今天的日期是'+ formatted_time +', '+ instruction + ' ###New Instruction: '
TypeError: can only concatenate str (not "function") to str
Traceback (most recent call last):
  File "/xxx/.local/lib/python3.10/site-packages/gradio/routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "/xxx/.local/lib/python3.10/site-packages/gradio/blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "/xxx/.local/lib/python3.10/site-packages/gradio/blocks.py", line 1117, in call_function
    prediction = await utils.async_iteration(iterator)
  File "/xxx/.local/lib/python3.10/site-packages/gradio/utils.py", line 350, in async_iteration
    return await iterator.__anext__()
  File "/xxx/.local/lib/python3.10/site-packages/gradio/utils.py", line 343, in __anext__
    return await anyio.to_thread.run_sync(
  File "/xxx/.local/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/xxx/.local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/xxx/.local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/xxx/.local/lib/python3.10/site-packages/gradio/utils.py", line 326, in run_sync_iterator_async
    return next(iterator)
  File "/xxx/.local/lib/python3.10/site-packages/gradio/utils.py", line 695, in gen_wrapper
    yield from f(*args, **kwargs)
  File "/xxx/Data-Copilot/app.py", line 168, in run
    for solving_step, img, res, df in generator:
  File "/xxx/Data-Copilot/app.py", line 64, in run
    yield next(gen)
  File "/xxx/Data-Copilot/main.py", line 378, in gradio_interface
    finally_text, img, output, df = thread.get_result()
  File "/xxx/Data-Copilot/main.py", line 40, in get_result
    return self.result
AttributeError: 'MyThread' object has no attribute 'result'```

**Comment by zwq2018** [comment]
看上去应该是因为 gpt 版本版本变化导致了输出格式没解析出来 ，具体 你 debug下

**Comment by zwq2018** [comment]
> @zwq2018 @ET-yzk 我是本地运行app.py，报上面这个错误，请问是什么原因导致的？
> 
> ```python
> ===============================Intent Detecting===========================================
> Exception in thread Thread-12:
> Traceback (most recent call last):
>   File "/xxx/miniconda3/envs/data_copilot/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
>     self.run()
>   File "/xxx/Data-Copilot/main.py", line 37, in run
>     self.result = self.func(*self.args)
>   File "/xxx/Data-Copilot/main.py", line 135, in run
>     prompt_intent_detection = prompt_intent_detection + '\n\n' + 'Instruction:' + '今天的日期是'+ formatted_time +', '+ instruction + ' ###New Instruction: '
> TypeError: can only concatenate str (not "function") to str
> Traceback (most recent call last):
>   File "/xxx/.local/lib/python3.10/site-packages/gradio/routes.py", line 488, in run_predict
>     output = await app.get_blocks().process_api(
>   File "/xxx/.local/lib/python3.10/site-packages/gradio/blocks.py", line 1431, in process_api
>     result = await self.call_function(
>   File "/xxx/.local/lib/python3.10/site-packages/gradio/blocks.py", line 1117, in call_function
>     prediction = await utils.async_iteration(iterator)
>   File "/xxx/.local/lib/python3.10/site-packages/gradio/utils.py", line 350, in async_iteration
>     return await iterator.__anext__()
>   File "/xxx/.local/lib/python3.10/site-packages/gradio/utils.py", line 343, in __anext__
>     return await anyio.to_thread.run_sync(
>   File "/xxx/.local/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
>     return await get_asynclib().run_sync_in_worker_thread(
>   File "/xxx/.local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
>     return await future
>   File "/xxx/.local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
>     result = context.run(func, *args)
>   File "/xxx/.local/lib/python3.10/site-packages/gradio/utils.py", line 326, in run_sync_iterator_async
>     return next(iterator)
>   File "/xxx/.local/lib/python3.10/site-packages/gradio/utils.py", line 695, in gen_wrapper
>     yield from f(*args, **kwargs)
>   File "/xxx/Data-Copilot/app.py", line 168, in run
>     for solving_step, img, res, df in generator:
>   File "/xxx/Data-Copilot/app.py", line 64, in run
>     yield next(gen)
>   File "/xxx/Data-Copilot/main.py", line 378, in gradio_interface
>     finally_text, img, output, df = thread.get_result()
>   File "/xxx/Data-Copilot/main.py", line 40, in get_result
>     return self.result
> AttributeError: 'MyThread' object has no attribute 'result'```
> ```

看上去应该是因为 gpt 版本版本变化导致了输出格式没解析出来 ，具体可能需要debug下

**Comment by zmsoft** [comment]
> > @zwq2018 @ET-yzk 我是本地运行app.py，报上面这个错误，请问是什么原因导致的？
> > ```python
> > ===============================Intent Detecting===========================================
> > Exception in thread Thread-12:
> > Traceback (most recent call last):
> >   File "/xxx/miniconda3/envs/data_copilot/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
> >     self.run()
> >   File "/xxx/Data-Copilot/main.py", line 37, in run
> >     self.result = self.func(*self.args)
> >   File "/xxx/Data-Copilot/main.py", line 135, in run
> >     prompt_intent_detection = prompt_intent_detection + '\n\n' + 'Instruction:' + '今天的日期是'+ formatted_time +', '+ instruction + ' ###New Instruction: '
> > TypeError: can only concatenate str (not "function") to str
> > Traceback (most recent call last):
> >   File "/xxx/.local/lib/python3.10/site-packages/gradio/routes.py", line 488, in run_predict
> >     output = await app.get_blocks().process_api(
> >   File "/xxx/.local/lib/python3.10/site-packages/gradio/blocks.py", line 1431, in process_api
> >     result = await self.call_function(
> >   File "/xxx/.local/lib/python3.10/site-packages/gradio/blocks.py", line 1117, in call_function
> >     prediction = await utils.async_iteration(iterator)
> >   File "/xxx/.local/lib/python3.10/site-packages/gradio/utils.py", line 350, in async_iteration
> >     return await iterator.__anext__()
> >   File "/xxx/.local/lib/python3.10/site-packages/gradio/utils.py", line 343, in __anext__
> >     return await anyio.to_thread.run_sync(
> >   File "/xxx/.local/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
> >     return await get_asynclib().run_sync_in_worker_thread(
> >   File "/xxx/.local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
> >     return await future
> >   File "/xxx/.local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
> >     result = context.run(func, *args)
> >   File "/xxx/.local/lib/python3.10/site-packages/gradio/utils.py", line 326, in run_sync_iterator_async
> >     return next(iterator)
> >   File "/xxx/.local/lib/python3.10/site-packages/gradio/utils.py", line 695, in gen_wrapper
> >     yield from f(*args, **kwargs)
> >   File "/xxx/Data-Copilot/app.py", line 168, in run
> >     for solving_step, img, res, df in generator:
> >   File "/xxx/Data-Copilot/app.py", line 64, in run
> >     yield next(gen)
> >   File "/xxx/Data-Copilot/main.py", line 378, in gradio_interface
> >     finally_text, img, output, df = thread.get_result()
> >   File "/xxx/Data-Copilot/main.py", line 40, in get_result
> >     return self.result
> > AttributeError: 'MyThread' object has no attribute 'result'```
> > ```
> 
> 看上去应该是因为 gpt 版本版本变化导致了输出格式没解析出来 ，具体可能需要debug下

```python 
main.py L135
prompt_intent_detection = prompt_intent_detection + '\n\n' + 'Instruction:' + '今天的日期是'+ formatted_time +', '+ instruction + ' ###New Instruction: ' 
```

@zwq2018 请教一下，这句代码是在做什么操作？
这句代码得到了以下的错误：
```python
TypeError: can only concatenate str (not "function") to str
```

**Comment by zwq2018** [comment]
就是把今天的时间 到 prompt 里吧  你debug 下哪个不是 str

**Comment by zwq2018** [comment]
> > > @zwq2018 @ET-yzk 我是本地运行app.py，报上面这个错误，请问是什么原因导致的？
> > > ```python
> > > ===============================Intent Detecting===========================================
> > > Exception in thread Thread-12:
> > > Traceback (most recent call last):
> > >   File "/xxx/miniconda3/envs/data_copilot/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
> > >     self.run()
> > >   File "/xxx/Data-Copilot/main.py", line 37, in run
> > >     self.result = self.func(*self.args)
> > >   File "/xxx/Data-Copilot/main.py", line 135, in run
> > >     prompt_intent_detection = prompt_intent_detection + '\n\n' + 'Instruction:' + '今天的日期是'+ formatted_time +', '+ instruction + ' ###New Instruction: '
> > > TypeError: can only concatenate str (not "function") to str
> > > Traceback (most recent call last):
> > >   File "/xxx/.local/lib/python3.10/site-packages/gradio/routes.py", line 488, in run_predict
> > >     output = await app.get_blocks().process_api(
> > >   File "/xxx/.local/lib/python3.10/site-packages/gradio/blocks.py", line 1431, in process_api
> > >     result = await self.call_function(
> > >   File "/xxx/.local/lib/python3.10/site-packages/gradio/blocks.py", line 1117, in call_function
> > >     prediction = await utils.async_iteration(iterator)
> > >   File "/xxx/.local/lib/python3.10/site-packages/gradio/utils.py", line 350, in async_iteration
> > >     return await iterator.__anext__()
> > >   File "/xxx/.local/lib/python3.10/site-packages/gradio/utils.py", line 343, in __anext__
> > >     return await anyio.to_thread.run_sync(
> > >   File "/xxx/.local/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
> > >     return await get_asynclib().run_sync_in_worker_thread(
> > >   File "/xxx/.local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
> > >     return await future
> > >   File "/xxx/.local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
> > >     result = context.run(func, *args)
> > >   File "/xxx/.local/lib/python3.10/site-packages/gradio/utils.py", line 326, in run_sync_iterator_async
> > >     return next(iterator)
> > >   File "/xxx/.local/lib/python3.10/site-packages/gradio/utils.py", line 695, in gen_wrapper
> > >     yield from f(*args, **kwargs)
> > >   File "/xxx/Data-Copilot/app.py", line 168, in run
> > >     for solving_step, img, res, df in generator:
> > >   File "/xxx/Data-Copilot/app.py", line 64, in run
> > >     yield next(gen)
> > >   File "/xxx/Data-Copilot/main.py", line 378, in gradio_interface
> > >     finally_text, img, output, df = thread.get_result()
> > >   File "/xxx/Data-Copilot/main.py", line 40, in get_result
> > >     return self.result
> > > AttributeError: 'MyThread' object has no attribute 'result'```
> > > ```
> > 
> > 
> > 看上去应该是因为 gpt 版本版本变化导致了输出格式没解析出来 ，具体可能需要debug下
> 
> ```python
> main.py L135
> prompt_intent_detection = prompt_intent_detection + '\n\n' + 'Instruction:' + '今天的日期是'+ formatted_time +', '+ instruction + ' ###New Instruction: ' 
> ```
> 
> @zwq2018 请教一下，这句代码是在做什么操作？ 这句代码得到了以下的错误：
> 
> ```python
> TypeError: can only concatenate str (not "function") to str
> ```

可以看看论文 。里面介绍的比较清楚
