### ISSUE TITLE
KeyError: 'result2'

### ISSUE THREAD

**Issue by wqyliyang** [zwq2018/Data-Copilot#6]
启动main.py 后 报如下的异常：

===============================Intent Detecting===========================================
2023-06-28 09:36:54
new_instruction: 预测未来中国4个季度的GDP增长率，展示基于2023年06月27日的数据预测未来4个季度的GDP增长率并打印表格
===============================Task Planing===========================================
2023-06-28 09:37:00
economic_task : 获取从20230627到20240627的季度GDP数据并预测未来4个季度的增长率
visualization_task : 打印未来4个季度的GDP增长率预测数据表格
===============================Tool select and using Stage===========================================
2023-06-28 09:37:05
==================

step: step1=
content: {
 "arg1": ["20230627","20240627","gdp_yoy"],
 "function1": "get_GDP_data",
 "output1": "result1",
 "description1": "gdp同比增速数据"
}
It has parallel steps: 1.0
Generated an exception: 抱歉，您没有访问该接口的权限，权限的具体详情访问：https://tushare.pro/document/1?doc_id=108。
==================

step: step2=
content: {
 "arg1": ["result1","gdp_yoy",4],
 "function1": "predict_next_value",
 "output1": "result2",
 "description1": "未来4个季度gdp同比增速数据预测数据"
}
It has parallel steps: 1.0
Generated an exception: 'result1'
===============================Visualization Stage===========================================
11111111111111111111111111111111111111
input1
['result2']
{}
Traceback (most recent call last):
  File "/home/Data-Copilot/Data-Copilot/main.py", line 390, in <module>
    output, image, df , output_result = run(instruction, send_chat_request_Azure = openai_call, openai_key=openai_key, api_base='', engine='')
  File "/home/Data-Copilot/Data-Copilot/main.py", line 283, in run
    Previous_result[rename] = result_buffer[output_name][1]
KeyError: 'result2'

**Comment by zwq2018** [comment]
这个问题应该是你本地跑tushare权限不够。你新注册的tushare应该积分不够，最好积分在2000
