### ISSUE TITLE
利用大模型进行接口设计的开源计划

### ISSUE THREAD

**Issue by DXQer** [zwq2018/Data-Copilot#7]
感谢您的开源工作！
论文中提到，该工作可以分为两部分，第一部分为用大模型进行接口设计，第二部分为对用户需求进行分析处理并得到相关结果。我看到开源代码中更多的是关于第二部分的体现，想问一下第一部分利用大模型进行接口设计的代码是否有计划开源？大概什么时候？

**Comment by zwq2018** [comment]
对 现在代码都是第二部分，基于已经设计好的接口工具来调用，处理下游需求。接口设计部分这部分跟数据源和用户需求强相关，感觉开源意义不大。直接看论文里应该也能明白，所以没放那部分代码
