### ISSUE TITLE
Something went wrong Connection errored out.

### ISSUE THREAD

**Issue by wqyliyang** [zwq2018/Data-Copilot#8]
![image](https://github.com/zwq2018/Data-Copilot/assets/20261829/24c8a3b9-45bc-40d9-9134-252babb76d70)

**Comment by zwq2018** [comment]
I've tried it, there should be no problem with Hugging Face. Are you running the program locally?

**Comment by zwq2018** [comment]
This feels like you didn't input the OpenAI key or Tushare token locally

**Comment by wqyliyang** [comment]
报的上面的那个错误 我是基于gradio直接运行的app.py   而且在填写完openai和azure相关信息  点击OK按钮的时候也是直接报这个错

![image](https://github.com/zwq2018/Data-Copilot/assets/20261829/2be248d5-4f1f-40c4-8f63-dbc4c5ab8451)


另外 再问一下  基于gradio的运行方式 怎么填写Tushare token

**Comment by zwq2018** [comment]
tushare是通过环境变量获取,你配置到本地环境，然后通过os.getenv获取
