### ISSUE TITLE
local variable 'thread' referenced before assignment

### ISSUE THREAD

**Issue by wqyliyang** [zwq2018/Data-Copilot#9]
线程声明的是个局部变量  使用到的时候有问题启动有问题
![image](https://github.com/zwq2018/Data-Copilot/assets/20261829/2afecfb6-3f10-4879-97e6-fc91a907bc37)

![image](https://github.com/zwq2018/Data-Copilot/assets/20261829/62b9b704-1346-4f27-b9d8-8a0d7355b2e1)

**Comment by zwq2018** [comment]
嗯 这个问题主要源自你thread没有被定义。应该是两个条件都没有满足，你检查下你的key
